### ISSUE TITLE
import viser from 'viser' 用法求 词云（tag-cloud）实现方式

### ISSUE THREAD

**Issue by baiheinet** [viserjs/viser#115]
用主页的这种方式
```jsx
import viser from 'viser';
Viser({
  data: GDP_JSON,
  tooltip: true,
  axis: true,
  series: [{ quickType: 'bar', color: '#0088fe', position: 'year*gdp' }],
  chart: { width: 700, height: 400, container: 'viser-mount-1-1' },
});
```

能不能创建一个 词云（tag-cloud）

举个列子

**Comment by linhuiw** [comment]
可以参考 词云的 文档

https://viserjs.github.io/demo.html#/others/word-cloud

**Comment by evilucifero** [comment]
Firstly, we don't suggest to directly use viser in your project, because you need to maintain the lifecycle of chart like repaint, destory and so on. 

Secondly, if you use react, vue, angular, viser-* package will be more easily to be used.

After read the instruction above, you think the "pure viser" is still the only solution. You can write your JSON follow the instruction below: 

1. Pass data in JSON root as `data`
2. Let other chart's props pass into property `chart`
3. Base chart component like `legend`, `axis`, `tooltip`, pass into there own property.
4. All other shape should pass into `series`, set the shape name into quickType of single into item like `<Bar {...props} /> => { quicktype: 'bar', ...props }`
5. If multi component in same name like 2 `axis` or 2 shape in `series`, just use an array to combine them.

**Comment by evilucifero** [comment]
If viser-* is not as powerful as you wish, just issue.
If you need viser in other frameworks, issue is also welcomed. 

Sincerely.

**Comment by yutao331763646** [comment]
![image](https://user-images.githubusercontent.com/27717350/68444706-9de63c80-0212-11ea-8cbb-60eb04f058c7.png)
angular 词云是混乱的  react  vue正常
