### ISSUE TITLE
Chart y轴如何设置去掉小数刻度, 只保留整数刻度?

### ISSUE THREAD

**Issue by FaiChou** [viserjs/viser#130]
![chart](http://o7bkcj7d7.bkt.clouddn.com/markdown/1517889260034.png)

```
      <Chart
        height={200} width={300}
        data={listData} scale={[{dataKey: 'title'}]}
      >
        <Tooltip />
        <Axis />
        <Guide type="text" content={`${c} (小计${subTotal.number})`} position="bottom" />
        <Bar position="title*count" />
      </Chart>
```

没找到合适的Axis属性设置, 求解答.

**Comment by evilucifero** [comment]
You can set props `subTickCount` in Axis, while set props `min` and `max` in scale to set range of your y-axis.

Here is an example of guage. Although it isn't an cartesian chart, but the principle is same.

Hope that's helpful to you.

**Comment by evilucifero** [comment]
Here is another demo of bar chart, you can just change `tickInterval` from 20 to 1 to suit your case.

https://viserjs.github.io/demo.html#/bar/basic-column

**Comment by FaiChou** [comment]
@evilucifero 

Thanks.

But:

![wrong](http://o7bkcj7d7.bkt.clouddn.com/markdown/1517925902159.png)

![correct](http://o7bkcj7d7.bkt.clouddn.com/markdown/1517925865447.png)

in some cases, it shows correct.

And I setted the `tickInterval` props.

```
const scale = [{
  dataKey: 'title',
  tickInterval: 1,
  // range: [0, 1], 
}];
```

```
      <Chart
        height={200} width={300}
        data={listData} scale={scale}
      >
        <Tooltip />
        <Axis />
        <Guide type="text" content={`${c} (小计${subTotal.number})`} position="bottom" />
        <Bar position="title*count" />
      </Chart>
```

And I can't set `min` and `max` because the data was from api response. Sometimes it just 0,1,2 and sometimes it will reach up to 100.

**Comment by evilucifero** [comment]
Since your data is dynamic, `tickInterval` is not suitable anymore. If you the max data reach 100, the static `tickInterval` will cause the problem like below.

![image](https://user-images.githubusercontent.com/3679062/35895789-02108aba-0bf4-11e8-9120-48e6893f8e3d.png)

So, I think the property you really need is `tickCount`. You can set it as a small number to avoid y axis display demical.

```javascript
const scale = [{
  dataKey: 'title',
  tickCount: 3,
}];
```

Here is a demo. https://viserjs.github.io/demo.html#/facet/rect-facet

But one thing you should notice that decimal will still display is the data is very very small. 

![image](https://user-images.githubusercontent.com/3679062/35896017-1ce48b88-0bf5-11e8-981b-23d5f5586828.png)

**Comment by evilucifero** [comment]
I think what you really need is a property that could be called `tickMinInterval`. But sorry, we don't have a property like this till now. ToT
