### ISSUE TITLE
多级tree分面图，Facet的fields数组为7个时，饼状图开始完全消失不见了

### ISSUE THREAD

**Issue by TsangTszKin** [viserjs/viser#283]
多级tree分面图，Facet的fields数组为7个时，饼状图开始完全消失不见了
![image](https://user-images.githubusercontent.com/32698113/49574520-94f24880-f97b-11e8-95fe-912bc9f6b9d1.png)

**Comment by huxiaoyun** [comment]
@evilucifero    看看哦~

**Comment by evilucifero** [comment]
Most of the times, it due to lack of height. The more tree facet you need, the more height you should assign to chart. Just assign a higher 'height' value to avoid this case happen.

And in this case, the data in the demo don't have so many fields to start a facet analysis. In other words, you may need data with more fields.

Hopes it would be useful to you.
